-- We used Claude  ai to automate repetetive use of WHEN THEN Clause

ALTER TABLE CountryProductExportDetailsTable
ADD  COLUMN country_name TEXT;

UPDATE CountryProductExportDetailsTable
SET country_name = CASE iso3_code
    WHEN 'AFG' THEN 'Afghanistan'
    WHEN 'AGO' THEN 'Angola'
    WHEN 'ALB' THEN 'Albania'
    WHEN 'AND' THEN 'Andorra'
    WHEN 'ARG' THEN 'Argentina'
    WHEN 'ARM' THEN 'Armenia'
    WHEN 'ASM' THEN 'American Samoa'
    WHEN 'ATA' THEN 'Antarctica'
    WHEN 'ATG' THEN 'Antigua and Barbuda'
    WHEN 'AUS' THEN 'Australia'
    WHEN 'AUT' THEN 'Austria'
    WHEN 'AZE' THEN 'Azerbaijan'
    WHEN 'BDI' THEN 'Burundi'
    WHEN 'BEL' THEN 'Belgium'
    WHEN 'BGD' THEN 'Bangladesh'
    WHEN 'BGR' THEN 'Bulgaria'
    WHEN 'BHR' THEN 'Bahrain'
    WHEN 'BHS' THEN 'Bahamas'
    WHEN 'BIH' THEN 'Bosnia and Herzegovina'
    WHEN 'BLR' THEN 'Belarus'
    WHEN 'BLZ' THEN 'Belize'
    WHEN 'BMU' THEN 'Bermuda'
    WHEN 'BOL' THEN 'Bolivia'
    WHEN 'BRA' THEN 'Brazil'
    WHEN 'BRB' THEN 'Barbados'
    WHEN 'BRN' THEN 'Brunei'
    WHEN 'BTN' THEN 'Bhutan'
    WHEN 'BVT' THEN 'Bouvet Island'
    WHEN 'BWA' THEN 'Botswana'
    WHEN 'CAN' THEN 'Canada'
    WHEN 'CMR' THEN 'Cameroon'
    WHEN 'DZA' THEN 'Algeria'
    WHEN 'KHM' THEN 'Cambodia'
    WHEN 'MMR' THEN 'Myanmar'
    WHEN 'SLB' THEN 'Solomon Islands'
    WHEN 'VGB' THEN 'British Virgin Islands'
    ELSE NULL
END;


ALTER TABLE CountryEconomicRankingsTable
ADD COLUMN country_name TEXT;

UPDATE CountryEconomicRankingsTable
SET country_name = CASE iso3_code
    WHEN 'AFG' THEN 'Afghanistan'
    WHEN 'AGO' THEN 'Angola'
    WHEN 'ALB' THEN 'Albania'
    WHEN 'AND' THEN 'Andorra'
    WHEN 'ARE' THEN 'United Arab Emirates'
    WHEN 'ARG' THEN 'Argentina'
    WHEN 'ARM' THEN 'Armenia'
    WHEN 'ASM' THEN 'American Samoa'
    WHEN 'ATA' THEN 'Antarctica'
    WHEN 'ATG' THEN 'Antigua and Barbuda'
    WHEN 'AUS' THEN 'Australia'
    WHEN 'AUT' THEN 'Austria'
    WHEN 'AZE' THEN 'Azerbaijan'
    WHEN 'BDI' THEN 'Burundi'
    WHEN 'BEL' THEN 'Belgium'
    WHEN 'BEN' THEN 'Benin'
    WHEN 'BFA' THEN 'Burkina Faso'
    WHEN 'BGD' THEN 'Bangladesh'
    WHEN 'BGR' THEN 'Bulgaria'
    WHEN 'BHR' THEN 'Bahrain'
    WHEN 'BHS' THEN 'Bahamas'
    WHEN 'BIH' THEN 'Bosnia and Herzegovina'
    WHEN 'BLR' THEN 'Belarus'
    WHEN 'BLZ' THEN 'Belize'
    WHEN 'BMU' THEN 'Bermuda'
    WHEN 'BOL' THEN 'Bolivia'
    WHEN 'BRA' THEN 'Brazil'
    WHEN 'BRB' THEN 'Barbados'
    WHEN 'BRN' THEN 'Brunei'
    WHEN 'BTN' THEN 'Bhutan'
    WHEN 'BVT' THEN 'Bouvet Island'
    WHEN 'BWA' THEN 'Botswana'
    WHEN 'CAN' THEN 'Canada'
    WHEN 'CHE' THEN 'Switzerland'
    WHEN 'CHL' THEN 'Chile'
    WHEN 'CHN' THEN 'China'
    WHEN 'CIV' THEN 'Cote d''Ivoire'
    WHEN 'CMR' THEN 'Cameroon'
    WHEN 'COD' THEN 'Democratic Republic of the Congo'
    WHEN 'COG' THEN 'Republic of the Congo'
    WHEN 'COL' THEN 'Colombia'
    WHEN 'CRI' THEN 'Costa Rica'
    WHEN 'CUB' THEN 'Cuba'
    WHEN 'CYP' THEN 'Cyprus'
    WHEN 'CZE' THEN 'Czechia'
    WHEN 'DEU' THEN 'Germany'
    WHEN 'DNK' THEN 'Denmark'
    WHEN 'DOM' THEN 'Dominican Republic'
    WHEN 'DZA' THEN 'Algeria'
    WHEN 'ECU' THEN 'Ecuador'
    WHEN 'EGY' THEN 'Egypt'
    WHEN 'ESP' THEN 'Spain'
    WHEN 'EST' THEN 'Estonia'
    WHEN 'ETH' THEN 'Ethiopia'
    WHEN 'FIN' THEN 'Finland'
    WHEN 'FRA' THEN 'France'
    WHEN 'GAB' THEN 'Gabon'
    WHEN 'GBR' THEN 'United Kingdom'
    WHEN 'GEO' THEN 'Georgia'
    WHEN 'GHA' THEN 'Ghana'
    WHEN 'GIN' THEN 'Guinea'
    WHEN 'GNQ' THEN 'Equatorial Guinea'
    WHEN 'GRC' THEN 'Greece'
    WHEN 'GTM' THEN 'Guatemala'
    WHEN 'HKG' THEN 'Hong Kong'
    WHEN 'HND' THEN 'Honduras'
    WHEN 'HRV' THEN 'Croatia'
    WHEN 'HTI' THEN 'Haiti'
    WHEN 'HUN' THEN 'Hungary'
    WHEN 'IDN' THEN 'Indonesia'
    WHEN 'IND' THEN 'India'
    WHEN 'IRL' THEN 'Ireland'
    WHEN 'IRN' THEN 'Iran'
    WHEN 'IRQ' THEN 'Iraq'
    WHEN 'ISR' THEN 'Israel'
    WHEN 'ITA' THEN 'Italy'
    WHEN 'JAM' THEN 'Jamaica'
    WHEN 'JOR' THEN 'Jordan'
    WHEN 'JPN' THEN 'Japan'
    WHEN 'KAZ' THEN 'Kazakhstan'
    WHEN 'KEN' THEN 'Kenya'
    WHEN 'KGZ' THEN 'Kyrgyzstan'
    WHEN 'KHM' THEN 'Cambodia'
    WHEN 'KOR' THEN 'South Korea'
    WHEN 'KWT' THEN 'Kuwait'
    WHEN 'LAO' THEN 'Laos'
    WHEN 'LBN' THEN 'Lebanon'
    WHEN 'LBR' THEN 'Liberia'
    WHEN 'LBY' THEN 'Libya'
    WHEN 'LKA' THEN 'Sri Lanka'
    WHEN 'LTU' THEN 'Lithuania'
    WHEN 'LVA' THEN 'Latvia'
    WHEN 'MAR' THEN 'Morocco'
    WHEN 'MDA' THEN 'Moldova'
    WHEN 'MDG' THEN 'Madagascar'
    WHEN 'MEX' THEN 'Mexico'
    WHEN 'MKD' THEN 'North Macedonia'
    WHEN 'MLI' THEN 'Mali'
    WHEN 'MMR' THEN 'Myanmar'
    WHEN 'MNG' THEN 'Mongolia'
    WHEN 'MOZ' THEN 'Mozambique'
    WHEN 'MRT' THEN 'Mauritania'
    WHEN 'MUS' THEN 'Mauritius'
    WHEN 'MWI' THEN 'Malawi'
    WHEN 'MYS' THEN 'Malaysia'
    WHEN 'NAM' THEN 'Namibia'
    WHEN 'NER' THEN 'Niger'
    WHEN 'NGA' THEN 'Nigeria'
    WHEN 'NIC' THEN 'Nicaragua'
    WHEN 'NLD' THEN 'Netherlands'
    WHEN 'NOR' THEN 'Norway'
    WHEN 'NPL' THEN 'Nepal'
    WHEN 'NZL' THEN 'New Zealand'
    WHEN 'OMN' THEN 'Oman'
    WHEN 'PAK' THEN 'Pakistan'
    WHEN 'PAN' THEN 'Panama'
    WHEN 'PER' THEN 'Peru'
    WHEN 'PHL' THEN 'Philippines'
    WHEN 'PNG' THEN 'Papua New Guinea'
    WHEN 'POL' THEN 'Poland'
    WHEN 'PRT' THEN 'Portugal'
    WHEN 'PRY' THEN 'Paraguay'
    WHEN 'QAT' THEN 'Qatar'
    WHEN 'ROU' THEN 'Romania'
    WHEN 'RUS' THEN 'Russia'
    WHEN 'RWA' THEN 'Rwanda'
    WHEN 'SAU' THEN 'Saudi Arabia'
    WHEN 'SDN' THEN 'Sudan'
    WHEN 'SEN' THEN 'Senegal'
    WHEN 'SGP' THEN 'Singapore'
    WHEN 'SLB' THEN 'Solomon Islands'
    WHEN 'SLV' THEN 'El Salvador'
    WHEN 'SRB' THEN 'Serbia'
    WHEN 'SVK' THEN 'Slovakia'
    WHEN 'SVN' THEN 'Slovenia'
    WHEN 'SWE' THEN 'Sweden'
    WHEN 'SWZ' THEN 'Eswatini'
    WHEN 'TCD' THEN 'Chad'
    WHEN 'TGO' THEN 'Togo'
    WHEN 'THA' THEN 'Thailand'
    WHEN 'TJK' THEN 'Tajikistan'
    WHEN 'TKM' THEN 'Turkmenistan'
    WHEN 'TTO' THEN 'Trinidad and Tobago'
    WHEN 'TUN' THEN 'Tunisia'
    WHEN 'TUR' THEN 'Turkey'
    WHEN 'TWN' THEN 'Taiwan'
    WHEN 'TZA' THEN 'Tanzania'
    WHEN 'UGA' THEN 'Uganda'
    WHEN 'UKR' THEN 'Ukraine'
    WHEN 'URY' THEN 'Uruguay'
    WHEN 'USA' THEN 'United States'
    WHEN 'UZB' THEN 'Uzbekistan'
    WHEN 'VEN' THEN 'Venezuela'
    WHEN 'VGB' THEN 'British Virgin Islands'
    WHEN 'VNM' THEN 'Vietnam'
    WHEN 'YEM' THEN 'Yemen'
    WHEN 'ZAF' THEN 'South Africa'
    WHEN 'ZMB' THEN 'Zambia'
    WHEN 'ZWE' THEN 'Zimbabwe'
    ELSE NULL
END;

ALTER TABLE HarvardEconomicData
ADD country_name TEXT;

UPDATE HarvardEconomicData
SET country_name = CASE iso3_code
    WHEN 'ABW' THEN 'Aruba'
    WHEN 'AFG' THEN 'Afghanistan'
    WHEN 'AGO' THEN 'Angola'
    WHEN 'AIA' THEN 'Anguilla'
    WHEN 'ALB' THEN 'Albania'
    WHEN 'AND' THEN 'Andorra'
    WHEN 'ANS' THEN 'Anjouan'
    WHEN 'ANT' THEN 'Netherlands Antilles'
    WHEN 'ARE' THEN 'United Arab Emirates'
    WHEN 'ARG' THEN 'Argentina'
    WHEN 'ARM' THEN 'Armenia'
    WHEN 'ASM' THEN 'American Samoa'
    WHEN 'ATA' THEN 'Antarctica'
    WHEN 'ATF' THEN 'French Southern Territories'
    WHEN 'ATG' THEN 'Antigua and Barbuda'
    WHEN 'AUS' THEN 'Australia'
    WHEN 'AUT' THEN 'Austria'
    WHEN 'AZE' THEN 'Azerbaijan'
    WHEN 'BDI' THEN 'Burundi'
    WHEN 'BEL' THEN 'Belgium'
    WHEN 'BEN' THEN 'Benin'
    WHEN 'BES' THEN 'Bonaire, Sint Eustatius and Saba'
    WHEN 'BFA' THEN 'Burkina Faso'
    WHEN 'BGD' THEN 'Bangladesh'
    WHEN 'BGR' THEN 'Bulgaria'
    WHEN 'BHR' THEN 'Bahrain'
    WHEN 'BHS' THEN 'Bahamas'
    WHEN 'BIH' THEN 'Bosnia and Herzegovina'
    WHEN 'BLM' THEN 'Saint Barthélemy'
    WHEN 'BLR' THEN 'Belarus'
    WHEN 'BLZ' THEN 'Belize'
    WHEN 'BMU' THEN 'Bermuda'
    WHEN 'BOL' THEN 'Bolivia'
    WHEN 'BRA' THEN 'Brazil'
    WHEN 'BRB' THEN 'Barbados'
    WHEN 'BRN' THEN 'Brunei Darussalam'
    WHEN 'BTN' THEN 'Bhutan'
    WHEN 'BVT' THEN 'Bouvet Island'
    WHEN 'BWA' THEN 'Botswana'
    WHEN 'CAF' THEN 'Central African Republic'
    WHEN 'CAN' THEN 'Canada'
    WHEN 'CCK' THEN 'Cocos (Keeling) Islands'
    WHEN 'CHE' THEN 'Switzerland'
    WHEN 'CHL' THEN 'Chile'
    WHEN 'CHN' THEN 'China'
    WHEN 'CIV' THEN 'Côte d''Ivoire'
    WHEN 'CMR' THEN 'Cameroon'
    WHEN 'COD' THEN 'Democratic Republic of the Congo'
    WHEN 'COG' THEN 'Congo'
    WHEN 'COK' THEN 'Cook Islands'
    WHEN 'COL' THEN 'Colombia'
    WHEN 'COM' THEN 'Comoros'
    WHEN 'CPV' THEN 'Cabo Verde'
    WHEN 'CRI' THEN 'Costa Rica'
    WHEN 'CUB' THEN 'Cuba'
    WHEN 'CUW' THEN 'Curaçao'
    WHEN 'CXR' THEN 'Christmas Island'
    WHEN 'CYM' THEN 'Cayman Islands'
    WHEN 'CYP' THEN 'Cyprus'
    WHEN 'CZE' THEN 'Czechia'
    WHEN 'DEU' THEN 'Germany'
    WHEN 'DJI' THEN 'Djibouti'
    WHEN 'DMA' THEN 'Dominica'
    WHEN 'DNK' THEN 'Denmark'
    WHEN 'DOM' THEN 'Dominican Republic'
    WHEN 'DZA' THEN 'Algeria'
    WHEN 'ECU' THEN 'Ecuador'
    WHEN 'EGY' THEN 'Egypt'
    WHEN 'ERI' THEN 'Eritrea'
    WHEN 'ESP' THEN 'Spain'
    WHEN 'EST' THEN 'Estonia'
    WHEN 'ETH' THEN 'Ethiopia'
    WHEN 'FIN' THEN 'Finland'
    WHEN 'FJI' THEN 'Fiji'
    WHEN 'FLK' THEN 'Falkland Islands'
    WHEN 'FRA' THEN 'France'
    WHEN 'FRO' THEN 'Faroe Islands'
    WHEN 'FSM' THEN 'Micronesia'
    WHEN 'GAB' THEN 'Gabon'
    WHEN 'GBR' THEN 'United Kingdom'
    WHEN 'GEO' THEN 'Georgia'
    WHEN 'GHA' THEN 'Ghana'
    WHEN 'GIB' THEN 'Gibraltar'
    WHEN 'GIN' THEN 'Guinea'
    WHEN 'GMB' THEN 'Gambia'
    WHEN 'GNB' THEN 'Guinea-Bissau'
    WHEN 'GNQ' THEN 'Equatorial Guinea'
    WHEN 'GRC' THEN 'Greece'
    WHEN 'GRD' THEN 'Grenada'
    WHEN 'GRL' THEN 'Greenland'
    WHEN 'GTM' THEN 'Guatemala'
    WHEN 'GUM' THEN 'Guam'
    WHEN 'GUY' THEN 'Guyana'
    WHEN 'HKG' THEN 'Hong Kong'
    WHEN 'HMD' THEN 'Heard Island and McDonald Islands'
    WHEN 'HND' THEN 'Honduras'
    WHEN 'HRV' THEN 'Croatia'
    WHEN 'HTI' THEN 'Haiti'
    WHEN 'HUN' THEN 'Hungary'
    WHEN 'IDN' THEN 'Indonesia'
    WHEN 'IND' THEN 'India'
    WHEN 'IRL' THEN 'Ireland'
    WHEN 'IRN' THEN 'Iran'
    WHEN 'IRQ' THEN 'Iraq'
    WHEN 'ISL' THEN 'Iceland'
    WHEN 'ISR' THEN 'Israel'
    WHEN 'ITA' THEN 'Italy'
    WHEN 'JAM' THEN 'Jamaica'
    WHEN 'JOR' THEN 'Jordan'
    WHEN 'JPN' THEN 'Japan'
    WHEN 'KAZ' THEN 'Kazakhstan'
    WHEN 'KEN' THEN 'Kenya'
    WHEN 'KGZ' THEN 'Kyrgyzstan'
    WHEN 'KHM' THEN 'Cambodia'
    WHEN 'KIR' THEN 'Kiribati'
    WHEN 'KNA' THEN 'Saint Kitts and Nevis'
    WHEN 'KOR' THEN 'South Korea'
    WHEN 'KWT' THEN 'Kuwait'
    WHEN 'LAO' THEN 'Laos'
    WHEN 'LBN' THEN 'Lebanon'
    WHEN 'LBR' THEN 'Liberia'
    WHEN 'LBY' THEN 'Libya'
    WHEN 'LCA' THEN 'Saint Lucia'
    WHEN 'LKA' THEN 'Sri Lanka'
    WHEN 'LSO' THEN 'Lesotho'
    WHEN 'LTU' THEN 'Lithuania'
    WHEN 'LUX' THEN 'Luxembourg'
    WHEN 'LVA' THEN 'Latvia'
    WHEN 'MAC' THEN 'Macao'
    WHEN 'MAR' THEN 'Morocco'
    WHEN 'MDA' THEN 'Moldova'
    WHEN 'MDG' THEN 'Madagascar'
    WHEN 'MDV' THEN 'Maldives'
    WHEN 'MEX' THEN 'Mexico'
    WHEN 'MHL' THEN 'Marshall Islands'
    WHEN 'MKD' THEN 'North Macedonia'
    WHEN 'MLI' THEN 'Mali'
    WHEN 'MLT' THEN 'Malta'
    WHEN 'MMR' THEN 'Myanmar'
    WHEN 'MNE' THEN 'Montenegro'
    WHEN 'MNG' THEN 'Mongolia'
    WHEN 'MNP' THEN 'Northern Mariana Islands'
    WHEN 'MOZ' THEN 'Mozambique'
    WHEN 'MRT' THEN 'Mauritania'
    WHEN 'MSR' THEN 'Montserrat'
    WHEN 'MUS' THEN 'Mauritius'
    WHEN 'MWI' THEN 'Malawi'
    WHEN 'MYS' THEN 'Malaysia'
    WHEN 'NAM' THEN 'Namibia'
    WHEN 'NCL' THEN 'New Caledonia'
    WHEN 'NER' THEN 'Niger'
    WHEN 'NFK' THEN 'Norfolk Island'
    WHEN 'NGA' THEN 'Nigeria'
    WHEN 'NIC' THEN 'Nicaragua'
    WHEN 'NIU' THEN 'Niue'
    WHEN 'NLD' THEN 'Netherlands'
    WHEN 'NOR' THEN 'Norway'
    WHEN 'NPL' THEN 'Nepal'
    WHEN 'NRU' THEN 'Nauru'
    WHEN 'NZL' THEN 'New Zealand'
    WHEN 'OMN' THEN 'Oman'
    WHEN 'PAK' THEN 'Pakistan'
    WHEN 'PAN' THEN 'Panama'
    WHEN 'PCN' THEN 'Pitcairn'
    WHEN 'PER' THEN 'Peru'
    WHEN 'PHL' THEN 'Philippines'
    WHEN 'PLW' THEN 'Palau'
    WHEN 'PNG' THEN 'Papua New Guinea'
    WHEN 'POL' THEN 'Poland'
    WHEN 'PRK' THEN 'North Korea'
    WHEN 'PRT' THEN 'Portugal'
    WHEN 'PRY' THEN 'Paraguay'
    WHEN 'PSE' THEN 'Palestine'
    WHEN 'PYF' THEN 'French Polynesia'
    WHEN 'QAT' THEN 'Qatar'
    WHEN 'ROU' THEN 'Romania'
    WHEN 'RUS' THEN 'Russia'
    WHEN 'RWA' THEN 'Rwanda'
    WHEN 'SAU' THEN 'Saudi Arabia'
    WHEN 'SDN' THEN 'Sudan'
    WHEN 'SEN' THEN 'Senegal'
    WHEN 'SGP' THEN 'Singapore'
    WHEN 'SGS' THEN 'South Georgia and South Sandwich Islands'
    WHEN 'SHN' THEN 'Saint Helena'
    WHEN 'SLB' THEN 'Solomon Islands'
    WHEN 'SLE' THEN 'Sierra Leone'
    WHEN 'SLV' THEN 'El Salvador'
    WHEN 'SMR' THEN 'San Marino'
    WHEN 'SOM' THEN 'Somalia'
    WHEN 'SPM' THEN 'Saint Pierre and Miquelon'
    WHEN 'SRB' THEN 'Serbia'
    WHEN 'SSD' THEN 'South Sudan'
    WHEN 'STP' THEN 'Sao Tome and Principe'
    WHEN 'SUR' THEN 'Suriname'
    WHEN 'SVK' THEN 'Slovakia'
    WHEN 'SVN' THEN 'Slovenia'
    WHEN 'SWE' THEN 'Sweden'
    WHEN 'SWZ' THEN 'Eswatini'
    WHEN 'SXM' THEN 'Sint Maarten'
    WHEN 'SYC' THEN 'Seychelles'
    WHEN 'SYR' THEN 'Syria'
    WHEN 'TCA' THEN 'Turks and Caicos Islands'
    WHEN 'TCD' THEN 'Chad'
    WHEN 'TGO' THEN 'Togo'
    WHEN 'THA' THEN 'Thailand'
    WHEN 'TJK' THEN 'Tajikistan'
    WHEN 'TKL' THEN 'Tokelau'
    WHEN 'TKM' THEN 'Turkmenistan'
    WHEN 'TLS' THEN 'Timor-Leste'
    WHEN 'TON' THEN 'Tonga'
    WHEN 'TTO' THEN 'Trinidad and Tobago'
    WHEN 'TUN' THEN 'Tunisia'
    WHEN 'TUR' THEN 'Turkey'
    WHEN 'TUV' THEN 'Tuvalu'
    WHEN 'TWN' THEN 'Taiwan'
    WHEN 'TZA' THEN 'Tanzania'
    WHEN 'UGA' THEN 'Uganda'
    WHEN 'UKR' THEN 'Ukraine'
    WHEN 'URY' THEN 'Uruguay'
    WHEN 'USA' THEN 'United States'
    WHEN 'UZB' THEN 'Uzbekistan'
    WHEN 'VAT' THEN 'Vatican City'
    WHEN 'VCT' THEN 'Saint Vincent and the Grenadines'
    WHEN 'VEN' THEN 'Venezuela'
    WHEN 'VGB' THEN 'Virgin Islands (British)'
    WHEN 'VNM' THEN 'Vietnam'
    WHEN 'VUT' THEN 'Vanuatu'
    WHEN 'WSM' THEN 'Samoa'
    WHEN 'YEM' THEN 'Yemen'
    WHEN 'ZAF' THEN 'South Africa'
    WHEN 'ZMB' THEN 'Zambia'
    WHEN 'ZWE' THEN 'Zimbabwe'
    ELSE NULL
END;


ALTER TABLE countryproductexportdetailstable
ADD COLUMN  product_name TEXT;

UPDATE countryproductexportdetailstable
SET product_name = CASE product_id::INTEGER
    WHEN 650 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 651 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 652 THEN 'Copper Cathodes (Grade 3)'
    WHEN 653 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 654 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 655 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 656 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 657 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 658 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 659 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 660 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 661 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 662 THEN 'Thermal Coal (Grade 3)'
    WHEN 663 THEN 'Basmati White Rice (Grade 4)'
    WHEN 664 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 665 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 666 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 667 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 668 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 669 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 670 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 671 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 672 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 673 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 674 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 675 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 676 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 677 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 678 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 679 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 680 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 681 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 682 THEN 'Copper Cathodes (Grade 3)'
    WHEN 683 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 684 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 685 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 686 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 687 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 688 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 689 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 690 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 691 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 692 THEN 'Thermal Coal (Grade 3)'
    WHEN 693 THEN 'Basmati White Rice (Grade 4)'
    WHEN 694 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 695 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 696 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 697 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 698 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 699 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 700 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 701 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 702 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 703 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 704 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 705 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 706 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 707 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 708 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 709 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 710 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 711 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 712 THEN 'Copper Cathodes (Grade 3)'
    WHEN 713 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 714 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 715 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 716 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 717 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 718 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 719 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 720 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 721 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 722 THEN 'Thermal Coal (Grade 3)'
    WHEN 723 THEN 'Basmati White Rice (Grade 4)'
    WHEN 724 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 725 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 726 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 727 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 728 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 729 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 730 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 731 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 732 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 733 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 734 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 735 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 736 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 737 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 738 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 739 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 740 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 741 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 742 THEN 'Copper Cathodes (Grade 3)'
    WHEN 743 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 744 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 745 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 746 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 747 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 748 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 749 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 750 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 751 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 752 THEN 'Thermal Coal (Grade 3)'
    WHEN 753 THEN 'Basmati White Rice (Grade 4)'
    WHEN 754 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 755 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 756 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 757 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 758 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 759 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 760 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 761 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 762 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 763 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 764 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 765 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 766 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 767 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 768 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 769 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 770 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 771 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 772 THEN 'Copper Cathodes (Grade 3)'
    WHEN 773 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 774 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 775 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 776 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 777 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 778 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 779 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 780 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 781 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 782 THEN 'Thermal Coal (Grade 3)'
    WHEN 783 THEN 'Basmati White Rice (Grade 4)'
    WHEN 784 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 785 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 786 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 787 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 788 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 789 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 790 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 791 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 792 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 793 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 794 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 795 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 796 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 797 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 798 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 799 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 800 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 801 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 802 THEN 'Copper Cathodes (Grade 3)'
    WHEN 803 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 804 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 805 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 806 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 807 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 808 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 809 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 810 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 811 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 812 THEN 'Thermal Coal (Grade 3)'
    WHEN 813 THEN 'Basmati White Rice (Grade 4)'
    WHEN 814 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 815 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 816 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 817 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 818 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 819 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 820 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 821 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 822 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 823 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 824 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 825 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 826 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 827 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 828 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 829 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 830 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 831 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 832 THEN 'Copper Cathodes (Grade 3)'
    WHEN 833 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 834 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 835 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 836 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 837 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 838 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 839 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 840 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 841 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 842 THEN 'Thermal Coal (Grade 3)'
    WHEN 843 THEN 'Basmati White Rice (Grade 4)'
    WHEN 844 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 845 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 846 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 847 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 848 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 849 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 850 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 851 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 852 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 853 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 854 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 855 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 856 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 857 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 858 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 859 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 860 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 861 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 862 THEN 'Copper Cathodes (Grade 3)'
    WHEN 863 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 864 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 865 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 866 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 867 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 868 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 869 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 870 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 871 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 872 THEN 'Thermal Coal (Grade 3)'
    WHEN 873 THEN 'Basmati White Rice (Grade 4)'
    WHEN 874 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 875 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 876 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 877 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 878 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 879 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 880 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 881 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 882 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 883 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 884 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 885 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 886 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 887 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 888 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 889 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 890 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 891 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 892 THEN 'Copper Cathodes (Grade 3)'
    WHEN 893 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 894 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 895 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 896 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 897 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 898 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 899 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 900 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 901 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 902 THEN 'Thermal Coal (Grade 3)'
    WHEN 903 THEN 'Basmati White Rice (Grade 4)'
    WHEN 904 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 905 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 906 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 907 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 908 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 909 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 910 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 911 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 912 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 913 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 914 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 915 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 916 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 917 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 918 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 919 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 920 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 921 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 922 THEN 'Copper Cathodes (Grade 3)'
    WHEN 923 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 924 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 925 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 926 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 927 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 928 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 929 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 930 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 931 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 932 THEN 'Thermal Coal (Grade 3)'
    WHEN 933 THEN 'Basmati White Rice (Grade 4)'
    WHEN 934 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 935 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 936 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 937 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 938 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 939 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 940 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 941 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 942 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 943 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 944 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 945 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 946 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 947 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 948 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 949 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 950 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 951 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 952 THEN 'Copper Cathodes (Grade 3)'
    WHEN 953 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 954 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 955 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 956 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 957 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 958 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 959 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 960 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 961 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 962 THEN 'Thermal Coal (Grade 3)'
    WHEN 963 THEN 'Basmati White Rice (Grade 4)'
    WHEN 964 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 965 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 966 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 967 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 968 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 969 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 970 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 971 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 972 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 973 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 974 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 975 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 976 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 977 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 978 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 979 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 980 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 981 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 982 THEN 'Copper Cathodes (Grade 3)'
    WHEN 983 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 984 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 985 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 986 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 987 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 988 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 989 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 990 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 991 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 992 THEN 'Thermal Coal (Grade 3)'
    WHEN 993 THEN 'Basmati White Rice (Grade 4)'
    WHEN 994 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 995 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 996 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 997 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 998 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 999 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1000 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1001 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1002 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1003 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1004 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1005 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1006 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1007 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1008 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1009 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1010 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1011 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1012 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1013 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1014 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1015 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1016 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1017 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1018 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1019 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1020 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1021 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1022 THEN 'Thermal Coal (Grade 3)'
    WHEN 1023 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1024 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1025 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1026 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1027 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1028 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1029 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1030 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1031 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1032 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1033 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1034 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1035 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1036 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1037 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1038 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1039 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1040 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1041 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1042 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1043 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1044 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1045 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1046 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1047 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1048 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1049 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1050 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1051 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1052 THEN 'Thermal Coal (Grade 3)'
    WHEN 1053 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1054 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1055 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1056 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1057 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1058 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1059 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1060 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1061 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1062 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1063 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1064 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1065 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1066 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1067 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1068 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1069 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1070 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1071 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1072 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1073 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1074 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1075 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1076 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1077 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1078 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1079 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1080 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1081 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1082 THEN 'Thermal Coal (Grade 3)'
    WHEN 1083 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1084 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1085 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1086 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1087 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1088 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1089 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1090 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1091 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1092 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1093 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1094 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1095 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1096 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1097 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1098 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1099 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1100 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1101 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1102 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1103 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1104 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1105 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1106 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1107 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1108 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1109 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1110 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1111 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1112 THEN 'Thermal Coal (Grade 3)'
    WHEN 1113 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1114 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1115 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1116 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1117 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1118 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1119 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1120 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1121 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1122 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1123 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1124 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1125 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1126 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1127 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1128 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1129 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1130 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1131 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1132 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1133 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1134 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1135 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1136 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1137 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1138 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1139 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1140 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1141 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1142 THEN 'Thermal Coal (Grade 3)'
    WHEN 1143 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1144 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1145 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1146 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1147 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1148 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1149 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1150 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1151 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1152 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1153 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1154 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1155 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1156 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1157 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1158 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1159 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1160 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1161 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1162 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1163 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1164 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1165 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1166 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1167 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1168 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1169 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1170 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1171 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1172 THEN 'Thermal Coal (Grade 3)'
    WHEN 1173 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1174 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1175 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1176 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1177 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1178 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1179 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1180 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1181 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1182 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1183 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1184 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1185 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1186 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1187 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1188 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1189 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1190 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1191 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1192 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1193 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1194 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1195 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1196 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1197 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1198 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1199 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1200 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1201 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1202 THEN 'Thermal Coal (Grade 3)'
    WHEN 1203 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1204 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1205 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1206 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1207 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1208 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1209 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1210 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1211 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1212 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1213 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1214 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1215 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1216 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1217 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1218 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1219 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1220 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1221 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1222 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1223 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1224 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1225 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1226 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1227 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1228 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1229 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1230 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1231 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1232 THEN 'Thermal Coal (Grade 3)'
    WHEN 1233 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1234 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1235 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1236 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1237 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1238 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1239 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1240 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1241 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1242 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1243 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1244 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1245 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1246 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1247 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1248 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1249 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1250 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1251 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1252 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1253 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1254 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1255 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1256 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1257 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1258 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1259 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1260 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1261 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1262 THEN 'Thermal Coal (Grade 3)'
    WHEN 1263 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1264 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1265 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1266 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1267 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1268 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1269 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1270 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1271 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1272 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1273 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1274 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1275 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1276 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1277 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1278 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1279 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1280 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1281 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1282 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1283 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1284 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1285 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1286 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1287 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1288 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1289 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1290 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1291 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1292 THEN 'Thermal Coal (Grade 3)'
    WHEN 1293 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1294 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1295 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1296 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1297 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1298 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1299 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1300 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1301 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1302 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1303 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1304 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1305 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1306 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1307 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1308 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1309 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1310 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1311 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1312 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1313 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1314 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1315 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1316 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1317 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1318 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1319 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1320 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1321 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1322 THEN 'Thermal Coal (Grade 3)'
    WHEN 1323 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1324 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1325 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1326 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1327 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1328 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1329 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1330 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1331 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1332 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1333 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1334 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1335 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1336 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1337 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1338 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1339 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1340 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1341 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1342 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1343 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1344 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1345 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1346 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1347 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1348 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1349 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1350 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1351 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1352 THEN 'Thermal Coal (Grade 3)'
    WHEN 1353 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1354 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1355 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1356 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1357 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1358 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1359 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1360 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1361 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1362 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1363 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1364 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1365 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1366 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1367 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1368 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1369 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1370 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1371 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1372 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1373 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1374 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1375 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1376 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1377 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1378 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1379 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1380 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1381 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1382 THEN 'Thermal Coal (Grade 3)'
    WHEN 1383 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1384 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1385 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1386 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1387 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1388 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1389 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1390 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1391 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1392 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1393 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1394 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1395 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1396 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1397 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1398 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1399 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1400 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1401 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1402 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1403 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1404 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1405 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1406 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1407 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1408 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1409 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1410 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1411 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1412 THEN 'Thermal Coal (Grade 3)'
    WHEN 1413 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1414 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1415 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1416 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1417 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1418 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1419 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1420 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1421 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1422 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1423 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1424 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1425 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1426 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1427 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1428 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1429 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1430 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1431 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1432 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1433 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1434 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1435 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1436 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1437 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1438 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1439 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1440 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1441 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1442 THEN 'Thermal Coal (Grade 3)'
    WHEN 1443 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1444 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1445 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1446 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1447 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1448 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1449 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1450 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1451 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1452 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1453 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1454 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1455 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1456 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1457 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1458 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1459 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1460 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1461 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1462 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1463 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1464 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1465 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1466 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1467 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1468 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1469 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1470 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1471 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1472 THEN 'Thermal Coal (Grade 3)'
    WHEN 1473 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1474 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1475 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1476 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1477 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1478 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1479 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1480 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1481 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1482 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1483 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1484 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1485 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1486 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1487 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1488 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1489 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1490 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1491 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1492 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1493 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1494 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1495 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1496 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1497 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1498 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1499 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1500 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1501 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1502 THEN 'Thermal Coal (Grade 3)'
    WHEN 1503 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1504 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1505 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1506 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1507 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1508 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1509 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1510 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1511 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1512 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1513 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1514 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1515 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1516 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1517 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1518 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1519 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1520 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1521 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1522 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1523 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1524 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1525 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1526 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1527 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1528 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1529 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1530 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1531 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1532 THEN 'Thermal Coal (Grade 3)'
    WHEN 1533 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1534 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1535 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1536 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1537 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1538 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1539 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1540 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1541 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1542 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1543 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1544 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1545 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1546 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1547 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1548 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1549 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1550 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1551 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1552 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1553 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1554 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1555 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1556 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1557 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1558 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1559 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1560 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1561 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1562 THEN 'Thermal Coal (Grade 3)'
    WHEN 1563 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1564 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1565 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1566 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1567 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1568 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1569 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1570 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1571 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1572 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1573 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1574 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1575 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1576 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1577 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1578 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1579 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1580 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1581 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1582 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1583 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1584 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1585 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1586 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1587 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1588 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1589 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1590 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1591 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1592 THEN 'Thermal Coal (Grade 3)'
    WHEN 1593 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1594 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1595 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1596 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1597 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1598 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1599 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1600 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1601 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1602 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1603 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1604 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1605 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1606 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1607 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1608 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1609 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1610 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1611 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1612 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1613 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1614 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1615 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1616 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1617 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1618 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1619 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1620 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1621 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1622 THEN 'Thermal Coal (Grade 3)'
    WHEN 1623 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1624 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1625 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1626 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1627 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1628 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1629 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1630 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1631 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1632 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1633 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1634 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1635 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1636 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1637 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1638 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1639 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1640 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1641 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1642 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1643 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1644 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1645 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1646 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1647 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1648 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1649 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1650 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1651 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1652 THEN 'Thermal Coal (Grade 3)'
    WHEN 1653 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1654 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1655 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1656 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1657 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1658 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1659 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1660 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1661 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1662 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1663 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1664 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1665 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1666 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1667 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1668 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1669 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1670 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1671 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1672 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1673 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1674 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1675 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1676 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1677 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1678 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1679 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1680 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1681 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1682 THEN 'Thermal Coal (Grade 3)'
    WHEN 1683 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1684 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1685 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1686 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1687 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1688 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1689 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1690 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1691 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1692 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1693 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1694 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1695 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1696 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1697 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1698 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1699 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1700 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1701 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1702 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1703 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1704 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1705 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1706 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1707 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1708 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1709 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1710 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1711 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1712 THEN 'Thermal Coal (Grade 3)'
    WHEN 1713 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1714 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1715 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1716 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1717 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1718 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1719 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1720 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1721 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1722 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1723 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1724 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1725 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1726 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1727 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1728 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1729 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1730 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1731 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1732 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1733 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1734 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1735 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1736 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1737 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1738 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1739 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1740 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1741 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1742 THEN 'Thermal Coal (Grade 3)'
    WHEN 1743 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1744 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1745 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1746 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1747 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1748 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1749 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1750 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1751 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1752 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1753 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1754 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1755 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1756 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1757 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1758 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1759 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1760 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1761 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1762 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1763 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1764 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1765 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1766 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1767 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1768 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1769 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1770 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1771 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1772 THEN 'Thermal Coal (Grade 3)'
    WHEN 1773 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1774 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1775 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1776 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1777 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1778 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1779 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1780 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1781 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1782 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1783 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1784 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1785 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1786 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1787 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1788 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1789 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1790 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1791 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1792 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1793 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1794 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1795 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1796 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1797 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1798 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1799 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1800 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1801 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1802 THEN 'Thermal Coal (Grade 3)'
    WHEN 1803 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1804 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1805 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1806 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1807 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1808 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1809 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1810 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1811 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1812 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1813 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1814 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1815 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1816 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1817 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1818 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1819 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1820 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1821 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1822 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1823 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1824 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1825 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1826 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1827 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1828 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1829 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1830 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1831 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1832 THEN 'Thermal Coal (Grade 3)'
    WHEN 1833 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1834 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1835 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1836 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1837 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1838 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1839 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1840 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1841 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1842 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1843 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1844 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1845 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1846 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1847 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1848 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1849 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1850 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1851 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1852 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1853 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1854 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1855 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1856 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1857 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1858 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1859 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1860 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1861 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1862 THEN 'Thermal Coal (Grade 3)'
    WHEN 1863 THEN 'Basmati White Rice (Grade 4)'
    WHEN 1864 THEN 'Natural Rubber Sheets (Grade 5)'
    WHEN 1865 THEN 'Hydraulic Fluid Concentrate (Grade 1)'
    WHEN 1866 THEN 'Synthetic Textile Yarns (Grade 2)'
    WHEN 1867 THEN 'Industrial Grade Aluminum Sheets (Grade 3)'
    WHEN 1868 THEN 'Pharmaceutical Paracetamol (Grade 4)'
    WHEN 1869 THEN 'Polyethylene Terephthalate Resin (Grade 5)'
    WHEN 1870 THEN 'Unrefined Soybean Oil (Grade 1)'
    WHEN 1871 THEN 'Organic Arabica Coffee Beans (Grade 2)'
    WHEN 1872 THEN 'Semiconductor Integrated Circuits (Grade 3)'
    WHEN 1873 THEN 'Automotive Alloy Wheels (Grade 4)'
    WHEN 1874 THEN 'Crude Petroleum Oil (Grade 5)'
    WHEN 1875 THEN 'Refined Copper Wire (Grade 1)'
    WHEN 1876 THEN 'Raw Cotton Fibers (Grade 2)'
    WHEN 1877 THEN 'Stainless Steel Pipes (Grade 3)'
    WHEN 1878 THEN 'Precision Microcontrollers (Grade 4)'
    WHEN 1879 THEN 'Medical Grade Face Masks (Grade 5)'
    WHEN 1880 THEN 'Extra Virgin Olive Oil (Grade 1)'
    WHEN 1881 THEN 'Lithium-ion Battery Cells (Grade 2)'
    WHEN 1882 THEN 'Copper Cathodes (Grade 3)'
    WHEN 1883 THEN 'Iron Ore Pellets (Grade 4)'
    WHEN 1884 THEN 'Refined Palm Oil (Grade 5)'
    WHEN 1885 THEN 'Frozen Atlantic Salmon (Grade 1)'
    WHEN 1886 THEN 'Refined Cane Sugar (Grade 2)'
    WHEN 1887 THEN 'Liquefied Natural Gas (Grade 3)'
    WHEN 1888 THEN 'Polypropylene Polymers (Grade 4)'
    WHEN 1889 THEN 'Solar Photovoltaic Modules (Grade 5)'
    WHEN 1890 THEN 'Processed Cocoa Butter (Grade 1)'
    WHEN 1891 THEN 'High-Grade Wheat Flour (Grade 2)'
    WHEN 1892 THEN 'Thermal Coal (Grade 3)'
    ELSE product_name
END;